"""Generate a weekly analytics report from normalized trade data.

This script builds a markdown summary and a machine-readable CSV artifact from:
1. ``analysis/analysis_dataset.csv`` (canonical reporting source).
2. ``rejections/rejections_tracking.csv`` and
   ``opportunities/opportunity_candidates.csv`` (trend counts).
3. Pre-built rejection summary exports from ``analysis/reports`` generated by
   ``analysis/rejection_diagnostics.py``.

It outputs only human-review recommendations and does not apply any strategy
changes automatically.
"""

from __future__ import annotations

import argparse
import csv
from collections import Counter, defaultdict
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from pathlib import Path
from statistics import median

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ANALYSIS_DATASET = PROJECT_ROOT / "analysis" / "analysis_dataset.csv"
DEFAULT_SYMBOL_LOG = PROJECT_ROOT / "rejections" / "rejections_tracking.csv"
DEFAULT_CANDIDATE_LOG = PROJECT_ROOT / "opportunities" / "opportunity_candidates.csv"
DEFAULT_REPORTS_DIR = PROJECT_ROOT / "analysis" / "reports"

REPORT_CSV_COLUMNS = ["section", "dimension", "group", "metric", "value"]

REJECTION_COUNTER_EXCLUSIONS = {
    "timestamp",
    "symbol",
    "strategy_version",
    "total_rejections",
}


@dataclass
class MetricSummary:
    """Aggregate performance metrics for a population of closed trades."""

    trade_count: int
    win_rate: float
    avg_pnl: float
    median_pnl: float
    total_pnl: float
    max_drawdown_proxy: float


def load_csv_rows(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    """Load a CSV file and return (header, rows)."""
    with open(path, newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        return reader.fieldnames or [], list(reader)


def write_csv(path: Path, header: list[str], rows: Iterable[list[str]]) -> None:
    """Write CSV rows and create parent directories as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(header)
        writer.writerows(rows)


def parse_float(value: str) -> float | None:
    """Parse a float and return None when input is blank/invalid."""
    raw = (value or "").strip()
    if raw == "":
        return None
    try:
        return float(raw)
    except ValueError:
        return None


def as_int(value: str) -> int:
    """Convert text to integer, coercing blanks and invalid text to zero."""
    raw = (value or "").strip()
    if raw == "":
        return 0
    try:
        return int(float(raw))
    except ValueError:
        return 0


def as_bool(value: str) -> bool:
    """Parse common CSV boolean text values."""
    return (value or "").strip().lower() in {"true", "1", "yes", "y"}


def parse_iso_date(value: str) -> date | None:
    """Parse date/datetime-like text into a date object."""
    raw = (value or "").strip()
    if raw == "":
        return None
    candidate = raw[:10]
    try:
        return date.fromisoformat(candidate)
    except ValueError:
        return None


def filter_rows_by_date(
    rows: list[dict[str, str]],
    date_column: str,
    start_date: date | None,
    end_date: date | None,
) -> list[dict[str, str]]:
    """Filter rows by inclusive date window using one timestamp/date column."""
    if start_date is None and end_date is None:
        return rows

    filtered: list[dict[str, str]] = []
    for row in rows:
        row_date = parse_iso_date(row.get(date_column, ""))
        if row_date is None:
            continue
        if start_date is not None and row_date < start_date:
            continue
        if end_date is not None and row_date > end_date:
            continue
        filtered.append(row)
    return filtered


def safe_divide(numerator: float, denominator: float) -> float:
    """Return a safe division result, using 0.0 for zero denominators."""
    if denominator == 0:
        return 0.0
    return numerator / denominator


def normalize_width(value: str) -> str:
    """Normalize width into compact group labels."""
    number = parse_float(value)
    if number is None:
        return "(missing)"
    if float(number).is_integer():
        return str(int(number))
    return f"{number:.2f}"


def dte_band(value: str) -> str:
    """Bucket DTE into broad planning ranges."""
    number = parse_float(value)
    if number is None:
        return "(missing)"
    dte_value = int(round(number))
    if dte_value <= 7:
        return "00-07"
    if dte_value <= 21:
        return "08-21"
    if dte_value <= 45:
        return "22-45"
    return "46+"


def delta_band(value: str) -> str:
    """Bucket short delta by absolute magnitude."""
    number = parse_float(value)
    if number is None:
        return "(missing)"
    abs_delta = abs(number)
    if abs_delta < 0.10:
        return "<0.10"
    if abs_delta < 0.20:
        return "0.10-0.19"
    if abs_delta < 0.30:
        return "0.20-0.29"
    return ">=0.30"


def skew_bucket(value: str) -> str:
    """Bucket skew ratio for quick quality segmentation."""
    number = parse_float(value)
    if number is None:
        return "(missing)"
    if number < 0.90:
        return "<0.90"
    if number < 1.00:
        return "0.90-0.99"
    if number < 1.10:
        return "1.00-1.09"
    return ">=1.10"


def build_closed_trade_records(
    analysis_rows: list[dict[str, str]],
) -> list[dict[str, object]]:
    """Extract closed executed trades with parsed pnl and close date."""
    by_trade_id: dict[str, dict[str, object]] = {}
    fallback_records: list[dict[str, object]] = []

    records: list[dict[str, object]] = []
    for row in analysis_rows:
        if (row.get("trade_status") or "").strip().lower() != "closed":
            continue

        pnl = parse_float(row.get("profit_loss", ""))
        if pnl is None:
            continue

        close_date = parse_iso_date(row.get("close_date", ""))
        if close_date is None:
            close_date = parse_iso_date(row.get("entry_date", ""))
        if close_date is None:
            close_date = parse_iso_date(row.get("snapshot_ts", ""))
        if close_date is None:
            continue

        record = {"row": row, "pnl": pnl, "close_date": close_date}
        trade_id = (row.get("trade_id") or "").strip()
        if not trade_id:
            fallback_records.append(record)
            continue

        existing = by_trade_id.get(trade_id)
        if existing is None:
            by_trade_id[trade_id] = record
            continue

        # Prefer the selected candidate row when duplicates exist for one trade_id.
        existing_selected = as_bool(existing["row"].get("selected", ""))
        current_selected = as_bool(row.get("selected", ""))
        if current_selected and not existing_selected:
            by_trade_id[trade_id] = record

    records.extend(by_trade_id.values())
    records.extend(fallback_records)
    return records


def max_drawdown_proxy(trade_points: list[tuple[date, float]]) -> float:
    """Compute peak-to-trough drawdown on cumulative pnl as a risk proxy."""
    cumulative = 0.0
    peak = 0.0
    worst_drawdown = 0.0

    for _, pnl in sorted(trade_points, key=lambda point: point[0]):
        cumulative += pnl
        peak = max(peak, cumulative)
        drawdown = peak - cumulative
        worst_drawdown = max(worst_drawdown, drawdown)

    return worst_drawdown


def summarize_performance(records: list[dict[str, object]]) -> MetricSummary:
    """Aggregate core performance metrics from closed trade records."""
    pnls = [float(record["pnl"]) for record in records]
    trade_points = [
        (record["close_date"], float(record["pnl"]))
        for record in records
        if isinstance(record.get("close_date"), date)
    ]
    wins = [pnl for pnl in pnls if pnl > 0]

    if not pnls:
        return MetricSummary(
            trade_count=0,
            win_rate=0.0,
            avg_pnl=0.0,
            median_pnl=0.0,
            total_pnl=0.0,
            max_drawdown_proxy=0.0,
        )

    return MetricSummary(
        trade_count=len(pnls),
        win_rate=safe_divide(len(wins), len(pnls)),
        avg_pnl=sum(pnls) / len(pnls),
        median_pnl=median(pnls),
        total_pnl=sum(pnls),
        max_drawdown_proxy=max_drawdown_proxy(trade_points),
    )


def build_segment_summaries(
    records: list[dict[str, object]],
    key_fn: Callable[[dict[str, str]], str],
    top_n: int,
) -> list[dict[str, object]]:
    """Build grouped performance summaries and return top groups by count."""
    grouped: dict[str, list[dict[str, object]]] = defaultdict(list)
    for record in records:
        row = record["row"]
        if not isinstance(row, dict):
            continue
        grouped[key_fn(row)].append(record)

    summary_rows: list[dict[str, object]] = []
    for group_name, group_records in grouped.items():
        stats = summarize_performance(group_records)
        summary_rows.append(
            {
                "group": group_name,
                "trade_count": stats.trade_count,
                "win_rate": stats.win_rate,
                "avg_pnl": stats.avg_pnl,
                "median_pnl": stats.median_pnl,
                "total_pnl": stats.total_pnl,
                "max_drawdown_proxy": stats.max_drawdown_proxy,
            }
        )

    summary_rows.sort(
        key=lambda row: (-int(row["trade_count"]), -float(row["total_pnl"]))
    )
    return summary_rows[:top_n]


def summarize_symbol_reasons(
    header: list[str], rows: list[dict[str, str]]
) -> Counter[str]:
    """Aggregate symbol-level reason counters from tracking logs."""
    totals: Counter[str] = Counter()
    counter_columns = [
        column for column in header if column not in REJECTION_COUNTER_EXCLUSIONS
    ]
    for row in rows:
        for column in counter_columns:
            totals[column] += as_int(row.get(column, "0"))
    return totals


def summarize_candidate_reasons(rows: list[dict[str, str]]) -> Counter[str]:
    """Aggregate candidate-level primary rejection reasons."""
    totals: Counter[str] = Counter()
    for row in rows:
        if (row.get("candidate_status") or "").strip().lower() != "rejected":
            continue
        reason = (row.get("rejection_reason_primary") or "").strip() or "(blank)"
        totals[reason] += 1
    return totals


def build_daily_rejection_trend(
    symbol_rows: list[dict[str, str]],
    candidate_rows: list[dict[str, str]],
    symbol_date_column: str,
    candidate_date_column: str,
) -> list[dict[str, object]]:
    """Build per-day rejection trend rows from both retained logs."""
    trend: dict[date, dict[str, int]] = defaultdict(
        lambda: {"symbol_rejections": 0, "candidate_rejections": 0}
    )

    for row in symbol_rows:
        day = parse_iso_date(row.get(symbol_date_column, ""))
        if day is None:
            continue
        trend[day]["symbol_rejections"] += as_int(row.get("total_rejections", "0"))

    for row in candidate_rows:
        if (row.get("candidate_status") or "").strip().lower() != "rejected":
            continue
        day = parse_iso_date(row.get(candidate_date_column, ""))
        if day is None:
            continue
        trend[day]["candidate_rejections"] += 1

    rows: list[dict[str, object]] = []
    for day in sorted(trend):
        symbol_total = trend[day]["symbol_rejections"]
        candidate_total = trend[day]["candidate_rejections"]
        rows.append(
            {
                "date": day.isoformat(),
                "symbol_rejections": symbol_total,
                "candidate_rejections": candidate_total,
                "candidate_to_symbol_ratio": safe_divide(
                    float(candidate_total), float(symbol_total)
                ),
            }
        )

    return rows


def load_rejection_export(path: Path, key_column: str) -> list[dict[str, object]]:
    """Load a rejection export CSV and normalize source/key/count rows."""
    _, rows = load_csv_rows(path)
    normalized: list[dict[str, object]] = []

    for row in rows:
        source = (row.get("source") or "").strip() or "(unknown)"
        key = (row.get(key_column) or "").strip() or "(blank)"
        count = as_int(row.get("count", "0"))
        normalized.append({"source": source, "key": key, "count": count})

    totals_by_source: dict[str, int] = defaultdict(int)
    for item in normalized:
        totals_by_source[str(item["source"])] += int(item["count"])

    for item in normalized:
        total = totals_by_source[str(item["source"])]
        item["share"] = safe_divide(float(item["count"]), float(total))

    normalized.sort(key=lambda item: (str(item["source"]), -int(item["count"])))
    return normalized


def build_rolling_window_metrics(
    closed_records: list[dict[str, object]],
    windows_days: tuple[int, ...] = (7, 14, 30),
) -> list[dict[str, object]]:
    """Compute rolling window performance metrics (win rate, PnL, trade count).

    Parameters
    ----------
    closed_records : list
        List of dicts with 'close_date' and 'pnl' keys.
    windows_days : tuple
        Rolling window sizes in days (default: 7, 14, 30).

    Returns
    -------
    list of dicts with keys: window_days, trade_count, win_rate, avg_pnl, total_pnl
    """
    if not closed_records:
        return []

    results = []
    today = date.today()

    for window_days in windows_days:
        cutoff = today - timedelta(days=window_days)
        window_records = [
            r
            for r in closed_records
            if isinstance(r.get("close_date"), date) and r["close_date"] >= cutoff
        ]

        if not window_records:
            results.append(
                {
                    "window_days": window_days,
                    "trade_count": 0,
                    "win_rate": 0.0,
                    "avg_pnl": 0.0,
                    "total_pnl": 0.0,
                }
            )
            continue

        pnls = [float(r["pnl"]) for r in window_records]
        wins = [p for p in pnls if p > 0]

        results.append(
            {
                "window_days": window_days,
                "trade_count": len(pnls),
                "win_rate": safe_divide(len(wins), len(pnls)),
                "avg_pnl": sum(pnls) / len(pnls),
                "total_pnl": sum(pnls),
            }
        )

    return results


def build_rolling_rejection_trends(
    symbol_rows: list[dict[str, str]],
    candidate_rows: list[dict[str, str]],
    symbol_date_column: str,
    candidate_date_column: str,
    windows_days: tuple[int, ...] = (7, 14, 30),
) -> list[dict[str, object]]:
    """Compute rolling rejection counts by window.

    Returns list of rolling window summaries.
    """
    if not symbol_rows and not candidate_rows:
        return []

    results = []
    today = date.today()

    for window_days in windows_days:
        cutoff = today - timedelta(days=window_days)

        symbol_count = sum(
            as_int(row.get("total_rejections", "0"))
            for row in symbol_rows
            if parse_iso_date(row.get(symbol_date_column, ""))
            and parse_iso_date(row.get(symbol_date_column, "")) >= cutoff
        )

        candidate_count = sum(
            1
            for row in candidate_rows
            if (row.get("candidate_status") or "").strip().lower() == "rejected"
            and parse_iso_date(row.get(candidate_date_column, ""))
            and parse_iso_date(row.get(candidate_date_column, "")) >= cutoff
        )

        results.append(
            {
                "window_days": window_days,
                "symbol_rejections": symbol_count,
                "candidate_rejections": candidate_count,
                "ratio": safe_divide(float(candidate_count), float(symbol_count)),
            }
        )

    return results


def load_latest_rankings(
    reports_dir: Path, max_count: int = 10
) -> list[dict[str, str]]:
    """Load the most recent ranking CSVs from reports_dir.

    Returns concatenated list of ranking rows from multiple runs.
    """
    import glob

    ranking_files = sorted(
        glob.glob(str(reports_dir / "opportunity_rankings_*.csv")),
        reverse=True,
    )[:max_count]

    all_rankings = []
    for filepath in ranking_files:
        try:
            with open(filepath, newline="", encoding="utf-8") as fh:
                all_rankings.extend(list(csv.DictReader(fh)))
        except Exception:
            continue

    return all_rankings


def make_spread_key(row: dict[str, str]) -> tuple:
    """Create a normalized match key for a spread from a row dict."""
    return (
        (row.get("symbol") or "").strip(),
        (row.get("expiration_date") or "").strip(),
        (row.get("short_strike") or "").strip(),
        (row.get("long_strike") or "").strip(),
    )


def build_ranking_quality_backtest(
    analysis_rows: list[dict[str, str]],
    ranking_rows: list[dict[str, str]],
    percentile_boundaries: tuple[float, ...] = (0.25, 0.75),
) -> list[dict[str, object]]:
    """Compare realized outcomes across ranking percentile buckets.

    Parameters
    ----------
    analysis_rows : list
        Rows from analysis_dataset.csv with trade outcomes.
    ranking_rows : list
        Rows from opportunity_rankings_*.csv with rank scores.
    percentile_boundaries : tuple
        Percentile cutoff points for bucketing (e.g., (0.25, 0.75) = top 25%, middle 50%, bottom 25%).

    Returns
    -------
    list of dicts with keys: percentile_label, trade_count, win_rate, avg_pnl, total_pnl
    """
    if not ranking_rows or not analysis_rows:
        return []

    # Filter to closed executed trades with outcomes
    closed_trade_map = {}
    for row in analysis_rows:
        if (row.get("trade_status") or "").strip().lower() != "closed":
            continue

        pnl = parse_float(row.get("profit_loss", ""))
        if pnl is None:
            continue

        key = make_spread_key(row)
        closed_trade_map[key] = {"pnl": pnl, "row": row}

    if not closed_trade_map:
        return []

    # Join rankings with closed trades
    scored_outcomes = []
    for rank_row in ranking_rows:
        key = make_spread_key(rank_row)
        if key not in closed_trade_map:
            continue

        score = parse_float(rank_row.get("total_rank_score", ""))
        if score is None:
            continue

        pnl = closed_trade_map[key]["pnl"]
        scored_outcomes.append({"score": score, "pnl": pnl})

    if len(scored_outcomes) < 2:
        return []

    # Sort by score descending and segment by percentiles
    scored_outcomes.sort(key=lambda x: -x["score"])

    # Build labels for percentile segments based on sorted boundaries
    # With boundaries=(0.25, 0.75), after sorting descending:
    # idx[0]=25% -> segment 0 to 25% = top 25% (highest scores)
    # idx[1]=75% -> segment 25% to 75% = middle 50%
    # remaining -> segment 75% to 100% = bottom 25% (lowest scores)
    sorted_boundaries = sorted(percentile_boundaries)
    percentile_labels = [f"top_{int(sorted_boundaries[0] * 100)}%"]
    for i in range(1, len(sorted_boundaries)):
        prev_boundary = sorted_boundaries[i - 1]
        curr_boundary = sorted_boundaries[i]
        label = (
            f"middle_{int((curr_boundary - prev_boundary) * 100)}%"
            if i < len(sorted_boundaries)
            else f"bottom_{int((1 - curr_boundary) * 100)}%"
        )
        percentile_labels.append(label)
    if len(sorted_boundaries) > 0:
        last_boundary = sorted_boundaries[-1]
        percentile_labels.append(f"bottom_{int((1 - last_boundary) * 100)}%")

    results = []
    prev_idx = 0
    for i, boundary in enumerate(sorted_boundaries):
        idx = int(len(scored_outcomes) * boundary)
        segment = scored_outcomes[prev_idx:idx]

        if not segment:
            prev_idx = idx
            continue

        pnls = [item["pnl"] for item in segment]
        wins = [p for p in pnls if p > 0]

        results.append(
            {
                "percentile_label": percentile_labels[i],
                "trade_count": len(pnls),
                "win_rate": safe_divide(len(wins), len(pnls)),
                "avg_pnl": sum(pnls) / len(pnls),
                "total_pnl": sum(pnls),
            }
        )

        prev_idx = idx

    # Handle remaining bottom segment
    if prev_idx < len(scored_outcomes):
        segment = scored_outcomes[prev_idx:]
        pnls = [item["pnl"] for item in segment]
        wins = [p for p in pnls if p > 0]

        results.append(
            {
                "percentile_label": percentile_labels[-1],
                "trade_count": len(pnls),
                "win_rate": safe_divide(len(wins), len(pnls)),
                "avg_pnl": sum(pnls) / len(pnls),
                "total_pnl": sum(pnls),
            }
        )

    return results


def build_rolling_rejection_reason_trends(
    candidate_rows: list[dict[str, str]],
    symbol_rows: list[dict[str, str]],
    candidate_date_column: str,
    symbol_date_column: str,
    windows_days: tuple[int, ...] = (7, 14, 30),
) -> list[dict[str, object]]:
    """Build rolling window trends for individual rejection reasons.

    Computes count of each rejection reason per window to identify improving
    or worsening rejection bottlenecks.

    Parameters
    ----------
    candidate_rows : list
        Rows from opportunity_candidates.csv with rejection reasons.
    symbol_rows : list
        Rows from rejections_tracking.csv with rejection reason columns.
    candidate_date_column : str
        Column name for candidate timestamps.
    symbol_date_column : str
        Column name for symbol-level timestamps.
    windows_days : tuple
        Rolling window sizes (default: 7, 14, 30 days).

    Returns
    -------
    list of dicts with keys: window_days, reason_source, reason, count
    """
    if not candidate_rows and not symbol_rows:
        return []

    results = []
    today = date.today()

    # Extract candidate-level rejection reasons (from rejection_reason_primary column)
    for window_days in windows_days:
        cutoff = today - timedelta(days=window_days)
        window_candidate_reasons = Counter()

        for row in candidate_rows:
            if (row.get("candidate_status") or "").strip().lower() != "rejected":
                continue

            row_date = parse_iso_date(row.get(candidate_date_column, ""))
            if not row_date or row_date < cutoff:
                continue

            reason = (row.get("rejection_reason_primary") or "").strip()
            if reason:
                window_candidate_reasons[reason] += 1

        # Add top candidate reasons for this window
        for reason, count in window_candidate_reasons.most_common(20):
            results.append(
                {
                    "window_days": window_days,
                    "reason_source": "candidate_level",
                    "reason": reason,
                    "count": count,
                }
            )

    # Extract symbol-level rejection reasons (from rejection columns in tracking log)
    # Symbol log has numeric columns for each rejection reason
    if symbol_rows:
        # Get rejection reason column names (exclude non-reason columns)
        skip_columns = {
            "symbol",
            "strategy_version",
            "total_rejections",
            "timestamp",
            "date",
        }

        for window_days in windows_days:
            cutoff = today - timedelta(days=window_days)
            window_symbol_reasons = Counter()

            for row in symbol_rows:
                row_date = parse_iso_date(row.get(symbol_date_column, ""))
                if not row_date or row_date < cutoff:
                    continue

                # Sum all rejection reason columns for this row
                for reason_col, value in row.items():
                    if reason_col in skip_columns:
                        continue

                    count_val = as_int(value)
                    if count_val and count_val > 0:
                        window_symbol_reasons[reason_col] += count_val

            # Add top symbol-level reasons for this window
            for reason, count in window_symbol_reasons.most_common(20):
                results.append(
                    {
                        "window_days": window_days,
                        "reason_source": "symbol_level",
                        "reason": reason,
                        "count": count,
                    }
                )

    return results


def build_sensitivity_analysis(
    candidate_rows: list[dict[str, str]],
    symbol_rows: list[dict[str, str]],
    sensitivity_step: float = 0.2,
) -> list[dict[str, object]]:
    """Analyze impact of loosening top rejection bottlenecks.

    Estimates unlock potential by computing how many additional candidates
    could be accepted if the top N rejection reasons were removed.

    Parameters
    ----------
    candidate_rows : list
        Rows from opportunity_candidates.csv.
    symbol_rows : list
        Rows from rejections_tracking.csv.
    sensitivity_step : float
        Fraction (0-1) of rejections to analyze incrementally (e.g., 0.2 = 20%).

    Returns
    -------
    list of dicts with keys: scenario, unlock_candidate_pct, unlock_count,
                              top_reason, target_change
    """
    if not candidate_rows:
        return []

    # Count rejected candidates for unlock estimates.
    rejected_candidates = len(
        [
            r
            for r in candidate_rows
            if (r.get("candidate_status") or "").strip().lower() == "rejected"
        ]
    )

    if rejected_candidates == 0:
        return []

    # Build rejection reason frequency for candidates
    candidate_reason_freq = Counter()
    for row in candidate_rows:
        if (row.get("candidate_status") or "").strip().lower() == "rejected":
            reason = (row.get("rejection_reason_primary") or "").strip()
            if reason:
                candidate_reason_freq[reason] += 1

    if not candidate_reason_freq:
        return []

    results = []

    # Scenario 1: Remove top rejection reason
    if candidate_reason_freq.most_common(1):
        top_reason, top_count = candidate_reason_freq.most_common(1)[0]
        potential_unlock = min(top_count, int(rejected_candidates * sensitivity_step))
        pct_unlock = safe_divide(potential_unlock, rejected_candidates)
        results.append(
            {
                "scenario": f"Remove {top_reason}",
                "unlock_candidate_pct": pct_unlock,
                "unlock_count": potential_unlock,
                "top_reason": top_reason,
                "reason_count": top_count,
                "target_change": "loosen constraints",
            }
        )

    # Scenario 2: Remove top 2 reasons
    if len(candidate_reason_freq) >= 2:
        top_two_count = sum(
            count for reason, count in candidate_reason_freq.most_common(2)
        )
        potential_unlock = min(
            top_two_count, int(rejected_candidates * sensitivity_step * 2)
        )
        pct_unlock = safe_divide(potential_unlock, rejected_candidates)
        top_two_reasons = ", ".join(
            [reason for reason, _ in candidate_reason_freq.most_common(2)]
        )
        results.append(
            {
                "scenario": f"Remove top 2: {top_two_reasons}",
                "unlock_candidate_pct": pct_unlock,
                "unlock_count": potential_unlock,
                "top_reason": top_two_reasons,
                "reason_count": top_two_count,
                "target_change": "loosen constraints",
            }
        )

    # Scenario 3: Remove liquidity bottleneck (bid/ask width constraints)
    liquidity_reasons = [
        r
        for r, _ in candidate_reason_freq.items()
        if "bid_ask_width" in r.lower() or "liquidity" in r.lower()
    ]
    if liquidity_reasons:
        liquidity_count = sum(
            candidate_reason_freq.get(r, 0) for r in liquidity_reasons
        )
        potential_unlock = min(
            liquidity_count, int(rejected_candidates * sensitivity_step * 1.5)
        )
        pct_unlock = safe_divide(potential_unlock, rejected_candidates)
        results.append(
            {
                "scenario": "Widen acceptable bid/ask spreads",
                "unlock_candidate_pct": pct_unlock,
                "unlock_count": potential_unlock,
                "top_reason": "liquidity bottleneck",
                "reason_count": liquidity_count,
                "target_change": "increase MAX_BID_ASK_TOLERANCE",
            }
        )

    # Scenario 4: Relax premium requirements
    premium_reasons = [
        r
        for r, _ in candidate_reason_freq.items()
        if "credit" in r.lower() or "premium" in r.lower()
    ]
    if premium_reasons:
        premium_count = sum(candidate_reason_freq.get(r, 0) for r in premium_reasons)
        potential_unlock = min(
            premium_count, int(rejected_candidates * sensitivity_step * 1.25)
        )
        pct_unlock = safe_divide(potential_unlock, rejected_candidates)
        results.append(
            {
                "scenario": "Reduce min premium requirement",
                "unlock_candidate_pct": pct_unlock,
                "unlock_count": potential_unlock,
                "top_reason": "premium bottleneck",
                "reason_count": premium_count,
                "target_change": "decrease MIN_CREDIT_PER_WIDTH",
            }
        )

    return results


def build_candidate_ranking_impact(
    candidate_rows: list[dict[str, str]],
    ranking_rows: list[dict[str, str]],
    percentile_threshold: float = 0.75,
) -> list[dict[str, object]]:
    """Analyze which rejection reasons block high-scoring candidates.

    Identifies rejection bottlenecks by computing what % of top-percentile
    ranked candidates are filtered out by each rejection reason.

    Parameters
    ----------
    candidate_rows : list
        Rows from opportunity_candidates.csv with rejection reasons.
    ranking_rows : list
        Rows from opportunity_rankings_*.csv with scores.
    percentile_threshold : float
        Score percentile threshold (0-1) to identify "high-scoring" candidates.
        Default 0.75 means top 25%.

    Returns
    -------
    list of dicts with keys: rejection_reason, high_score_rejected_count,
                              total_rejected_count, high_score_pct, avg_score_rejected
    """
    if not candidate_rows or not ranking_rows:
        return []

    # Build map of (symbol, expiration_date, short_strike, long_strike) -> rank_score
    ranked_map = {}
    all_scores = []
    for row in ranking_rows:
        key = make_spread_key(row)
        score = parse_float(row.get("total_rank_score", ""))
        if score is not None:
            ranked_map[key] = score
            all_scores.append(score)

    if not all_scores:
        return []

    # Compute score threshold for "high-scoring" candidates
    all_scores.sort()
    threshold_idx = int(len(all_scores) * percentile_threshold)
    score_threshold = (
        all_scores[threshold_idx] if threshold_idx < len(all_scores) else all_scores[-1]
    )

    # Track rejection metrics per reason
    rejection_metrics = {}  # reason -> {high_count, total_count, scores}

    for row in candidate_rows:
        if (row.get("candidate_status") or "").strip().lower() != "rejected":
            continue

        key = make_spread_key(row)
        score = ranked_map.get(key)
        reason = (row.get("rejection_reason_primary") or "").strip()

        if not reason or score is None:
            continue

        if reason not in rejection_metrics:
            rejection_metrics[reason] = {
                "high_count": 0,
                "total_count": 0,
                "scores": [],
            }

        rejection_metrics[reason]["total_count"] += 1
        rejection_metrics[reason]["scores"].append(score)

        if score >= score_threshold:
            rejection_metrics[reason]["high_count"] += 1

    if not rejection_metrics:
        return []

    # Build results, sorted by % high-score rejections (descending)
    results = []
    for reason, metrics in rejection_metrics.items():
        high_score_pct = safe_divide(metrics["high_count"], metrics["total_count"])
        avg_score = (
            sum(metrics["scores"]) / len(metrics["scores"])
            if metrics["scores"]
            else 0.0
        )

        results.append(
            {
                "rejection_reason": reason,
                "high_score_rejected_count": metrics["high_count"],
                "total_rejected_count": metrics["total_count"],
                "high_score_pct": high_score_pct,
                "avg_score_rejected": avg_score,
            }
        )

    # Sort by high_score_pct descending to show worst bottlenecks first
    results.sort(key=lambda x: -x["high_score_pct"])
    return results


def recommendations(
    overall: MetricSummary,
    bucket_summary_rows: list[dict[str, object]],
    segment_rows: dict[str, list[dict[str, object]]],
) -> list[str]:
    """Create human-review recommendation lines without auto-apply behavior."""
    lines: list[str] = []

    if overall.trade_count == 0:
        lines.append(
            "No closed selected trades in window; defer threshold changes and "
            "extend the sample period before tuning."
        )
        lines.append("All recommendations are review-only and require manual approval.")
        return lines

    if overall.win_rate < 0.45:
        lines.append(
            "Review entry quality for lower-confidence setups; current win rate is "
            f"{overall.win_rate:.1%}, below a 45% review threshold."
        )
    if overall.max_drawdown_proxy > max(500.0, abs(overall.total_pnl) * 0.75):
        lines.append(
            "Review risk concentration by symbol/width; drawdown proxy is elevated "
            "relative to period pnl."
        )

    candidate_buckets = [
        row
        for row in bucket_summary_rows
        if str(row["source"]).strip().lower() == "candidate_level"
    ]
    if candidate_buckets:
        top_bucket = max(candidate_buckets, key=lambda row: int(row["count"]))
        if float(top_bucket["share"]) >= 0.35:
            lines.append(
                "Focus review on bucket "
                f"{top_bucket['key']} ({float(top_bucket['share']):.1%} of candidate "
                "rejections) to test whether guardrails are overly restrictive."
            )

    symbol_rows = segment_rows.get("symbol", [])
    if symbol_rows:
        weak = [
            row
            for row in symbol_rows
            if int(row["trade_count"]) >= 3 and float(row["avg_pnl"]) < 0
        ]
        if weak:
            symbols = ", ".join(str(row["group"]) for row in weak[:3])
            lines.append(
                "Prioritize human review of underperforming symbols with repeated "
                f"losses: {symbols}."
            )

    if not lines:
        lines.append(
            "No urgent changes indicated; continue current parameters and monitor the "
            "next weekly sample for stability."
        )

    lines.append("All recommendations are review-only and require manual approval.")
    return lines


def build_recommendation_impact_confidence(
    recommendation_lines: list[str],
    overall: MetricSummary,
    sensitivity_analysis_results: list[dict[str, object]],
    candidate_ranking_impact_results: list[dict[str, object]],
) -> list[dict[str, str]]:
    """Estimate expected impact and confidence for each recommendation."""
    rows: list[dict[str, str]] = []
    review_guardrail = (
        "All recommendations are review-only and require manual approval."
    )

    if overall.trade_count >= 20:
        base_confidence = "High"
    elif overall.trade_count >= 8:
        base_confidence = "Medium"
    else:
        base_confidence = "Low"

    top_unlock = max(
        sensitivity_analysis_results,
        key=lambda item: float(item.get("unlock_candidate_pct", 0.0)),
        default=None,
    )
    top_bottleneck = max(
        candidate_ranking_impact_results,
        key=lambda item: float(item.get("high_score_pct", 0.0)),
        default=None,
    )

    for recommendation in recommendation_lines:
        if recommendation == review_guardrail:
            continue

        expected_impact = (
            "Stability check and directional insight for next weekly sample."
        )
        confidence = base_confidence
        rationale = (
            f"Based on {overall.trade_count} closed trades in the reporting window."
        )

        lower = recommendation.lower()
        if "guardrails are overly restrictive" in lower and top_unlock is not None:
            unlock_count = int(top_unlock.get("unlock_count", 0))
            unlock_pct = float(top_unlock.get("unlock_candidate_pct", 0.0))
            scenario = str(top_unlock.get("scenario", "top rejection bottleneck"))
            expected_impact = f"Potentially unlock {unlock_count} additional candidates ({unlock_pct:.1%} of rejected)."
            confidence = (
                "High" if base_confidence == "High" and unlock_count >= 3 else "Medium"
            )
            rationale = f"Sensitivity scenario '{scenario}' shows measurable unlock potential in this window."
        elif "entry quality" in lower:
            expected_impact = "Improve win rate by reducing weak setup entries."
            if overall.trade_count < 8:
                confidence = "Low"
            rationale = "Current realized win rate is below the review threshold."
        elif "drawdown" in lower or "risk concentration" in lower:
            expected_impact = (
                "Reduce tail-loss concentration and smooth weekly PnL volatility."
            )
            confidence = "Medium" if overall.trade_count >= 6 else "Low"
            rationale = (
                "Drawdown proxy is elevated versus total PnL for the same period."
            )
        elif "underperforming symbols" in lower:
            expected_impact = (
                "Reduce repeat losses by tightening rules on weak symbol cohorts."
            )
            if (
                top_bottleneck is not None
                and float(top_bottleneck.get("high_score_pct", 0.0)) >= 0.35
            ):
                confidence = "Medium"
                rationale = "Repeated symbol-level weakness plus high-score rejection bottlenecks suggest tunable constraints."
            else:
                confidence = "Low" if overall.trade_count < 8 else "Medium"
                rationale = "Multiple trades in underperforming symbols indicate concentration risk."

        rows.append(
            {
                "recommendation": recommendation,
                "expected_impact": expected_impact,
                "confidence": confidence,
                "rationale": rationale,
            }
        )

    if not rows:
        rows.append(
            {
                "recommendation": "Continue current settings with manual review.",
                "expected_impact": "Maintain current risk posture while collecting more evidence.",
                "confidence": base_confidence,
                "rationale": f"No actionable recommendation candidates; sample includes {overall.trade_count} closed trades.",
            }
        )

    return rows


def markdown_table(headers: list[str], rows: list[list[str]]) -> list[str]:
    """Build a markdown table from headers and rows."""
    if not rows:
        return ["(no data)"]

    separator = ["---"] * len(headers)
    table_lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(separator) + " |",
    ]
    for row in rows:
        table_lines.append("| " + " | ".join(row) + " |")
    return table_lines


def format_metric(value: float, kind: str) -> str:
    """Format numeric metrics consistently for markdown and CSV outputs."""
    if kind == "percent":
        return f"{value:.2%}"
    if kind == "currency":
        return f"{value:.2f}"
    return f"{value:.4f}"


def build_execution_alignment_summary(
    closed_records: list[dict[str, object]],
) -> dict[str, object]:
    """Summarize exact vs shifted execution alignment for closed trades."""
    alignment_counts: Counter[str] = Counter()
    direction_counts: Counter[str] = Counter()
    trade_only_reason_counts: Counter[str] = Counter()
    daily_presence_counts: Counter[str] = Counter()
    daily_match_type_counts: Counter[str] = Counter()
    short_shift_abs: list[float] = []
    long_shift_abs: list[float] = []
    shifted_examples: list[dict[str, str]] = []

    for record in closed_records:
        row = record.get("row")
        if not isinstance(row, dict):
            continue

        alignment = (row.get("execution_alignment") or "").strip() or "unknown"
        direction = (row.get("shift_direction") or "").strip() or "unknown"
        alignment_counts[alignment] += 1
        direction_counts[direction] += 1

        in_daily = (row.get("was_in_daily_opportunities_file") or "").strip()
        if in_daily:
            daily_presence_counts[in_daily] += 1
        daily_match_type = (row.get("daily_opportunity_match_type") or "").strip()
        if daily_match_type:
            daily_match_type_counts[daily_match_type] += 1

        if alignment == "trade_only":
            reason = (row.get("trade_only_reason") or "").strip() or "unspecified"
            trade_only_reason_counts[reason] += 1

        if alignment != "shifted":
            continue

        short_shift = parse_float(row.get("short_strike_shift", ""))
        long_shift = parse_float(row.get("long_strike_shift", ""))
        if short_shift is not None:
            short_shift_abs.append(abs(short_shift))
        if long_shift is not None:
            long_shift_abs.append(abs(long_shift))

        shifted_examples.append(
            {
                "trade_id": (row.get("trade_id") or "").strip(),
                "symbol": (row.get("symbol") or "").strip(),
                "candidate_pair": (
                    f"{(row.get('short_strike') or '').strip()}/"
                    f"{(row.get('long_strike') or '').strip()}"
                ),
                "executed_pair": (
                    f"{(row.get('executed_short_strike') or '').strip()}/"
                    f"{(row.get('executed_long_strike') or '').strip()}"
                ),
                "direction": direction,
            }
        )

    return {
        "alignment_counts": alignment_counts,
        "direction_counts": direction_counts,
        "avg_short_shift_abs": (
            sum(short_shift_abs) / len(short_shift_abs) if short_shift_abs else 0.0
        ),
        "avg_long_shift_abs": (
            sum(long_shift_abs) / len(long_shift_abs) if long_shift_abs else 0.0
        ),
        "trade_only_reason_counts": trade_only_reason_counts,
        "daily_presence_counts": daily_presence_counts,
        "daily_match_type_counts": daily_match_type_counts,
        "shifted_examples": shifted_examples,
    }


def build_markdown_report(
    *,
    window_text: str,
    generated_at: str,
    total_rows: int,
    selected_rows: int,
    closed_records: list[dict[str, object]],
    overall: MetricSummary,
    segment_rows: dict[str, list[dict[str, object]]],
    rolling_window_metrics: list[dict[str, object]],
    rolling_rejection_trends: list[dict[str, object]],
    rolling_rejection_reason_trends: list[dict[str, object]],
    ranking_backtest_results: list[dict[str, object]],
    sensitivity_analysis_results: list[dict[str, object]],
    candidate_ranking_impact_results: list[dict[str, object]],
    symbol_reason_totals: Counter[str],
    candidate_reason_totals: Counter[str],
    trend_rows: list[dict[str, object]],
    reason_summary_rows: list[dict[str, object]],
    bucket_summary_rows: list[dict[str, object]],
    recommendation_lines: list[str],
    recommendation_impact_rows: list[dict[str, str]],
    markdown_output_path: Path,
    csv_output_path: Path,
) -> str:
    """Assemble the full markdown report text."""
    lines = [
        "# Weekly Trade Analytics Report",
        "",
        f"- Generated at: {generated_at}",
        f"- Date window: {window_text}",
        f"- Analysis dataset rows: {total_rows}",
        f"- Selected rows: {selected_rows}",
        f"- Closed trades analyzed: {len(closed_records)}",
        "",
        "## Executive Summary",
        f"- Win rate: {overall.win_rate:.2%}",
        f"- Average pnl per closed trade: {overall.avg_pnl:.2f}",
        f"- Median pnl per closed trade: {overall.median_pnl:.2f}",
        f"- Total pnl (closed trades): {overall.total_pnl:.2f}",
        f"- Max drawdown proxy: {overall.max_drawdown_proxy:.2f}",
        "",
        "## Rolling Trend Metrics",
    ]

    if rolling_window_metrics:
        rolling_table_rows = [
            [
                f"{item['window_days']}d",
                str(item["trade_count"]),
                f"{float(item['win_rate']):.2%}",
                f"{float(item['avg_pnl']):.2f}",
                f"{float(item['total_pnl']):.2f}",
            ]
            for item in rolling_window_metrics
        ]
        lines.extend(
            markdown_table(
                ["Window", "Trades", "Win Rate", "Avg PnL", "Total PnL"],
                rolling_table_rows,
            )
        )
    else:
        lines.append("(no closed trades in window)")

    lines.append("")
    lines.append("### Rolling Rejection Trends")
    if rolling_rejection_trends:
        rejection_trend_rows = [
            [
                f"{item['window_days']}d",
                str(item["symbol_rejections"]),
                str(item["candidate_rejections"]),
                f"{float(item['ratio']):.2f}",
            ]
            for item in rolling_rejection_trends
        ]
        lines.extend(
            markdown_table(
                [
                    "Window",
                    "Symbol Rejections",
                    "Candidate Rejections",
                    "Cand/Sym Ratio",
                ],
                rejection_trend_rows,
            )
        )
    else:
        lines.append("(no rejection data in window)")

    lines.extend(["", "### Rolling Rejection Reason Trends"])
    if rolling_rejection_reason_trends:
        # Group by window_days for better readability
        reason_trends_by_window = {}
        for item in rolling_rejection_reason_trends:
            window = item["window_days"]
            if window not in reason_trends_by_window:
                reason_trends_by_window[window] = []
            reason_trends_by_window[window].append(item)

        for window_days in sorted(reason_trends_by_window.keys(), reverse=True):
            lines.append(f"**{window_days}-day window:**")
            window_items = reason_trends_by_window[window_days]
            reason_rows = [
                [
                    item["reason_source"],
                    item["reason"],
                    str(item["count"]),
                ]
                for item in window_items[:15]  # Top 15 reasons per window
            ]
            lines.extend(
                markdown_table(
                    ["Source", "Reason", "Count"],
                    reason_rows,
                )
            )
            lines.append("")
    else:
        lines.append("(no rejection reason trend data in window)")

    execution_alignment_summary = build_execution_alignment_summary(closed_records)
    alignment_counts = execution_alignment_summary["alignment_counts"]
    shifted_count = int(alignment_counts.get("shifted", 0))
    exact_count = int(alignment_counts.get("exact", 0))
    trade_only_count = int(alignment_counts.get("trade_only", 0))

    lines.extend(["", "## Execution Alignment"])
    lines.append(
        "Shows whether executed trades matched suggested strikes exactly or were shifted "
        "(useful for tuning SKEW_WINDOW_OTM and SKEW_WINDOW_ITM)."
    )
    lines.extend(
        markdown_table(
            ["Alignment", "Count", "Share"],
            [
                [
                    "exact",
                    str(exact_count),
                    f"{safe_divide(exact_count, max(1, len(closed_records))):.1%}",
                ],
                [
                    "shifted",
                    str(shifted_count),
                    f"{safe_divide(shifted_count, max(1, len(closed_records))):.1%}",
                ],
                [
                    "trade_only",
                    str(trade_only_count),
                    f"{safe_divide(trade_only_count, max(1, len(closed_records))):.1%}",
                ],
            ],
        )
    )

    if shifted_count > 0:
        direction_counts = execution_alignment_summary["direction_counts"]
        lines.extend(
            [
                "",
                f"- Avg short strike shift (abs): {float(execution_alignment_summary['avg_short_shift_abs']):.2f}",
                f"- Avg long strike shift (abs): {float(execution_alignment_summary['avg_long_shift_abs']):.2f}",
                f"- OTM shifted trades: {int(direction_counts.get('otm_shift', 0))}",
                f"- ITM shifted trades: {int(direction_counts.get('itm_shift', 0))}",
                f"- Mixed shifted trades: {int(direction_counts.get('mixed_shift', 0))}",
                "",
                "### Shifted Trade Examples",
            ]
        )
        example_rows = [
            [
                item["symbol"],
                item["candidate_pair"],
                item["executed_pair"],
                item["direction"],
            ]
            for item in execution_alignment_summary["shifted_examples"][:10]
        ]
        lines.extend(
            markdown_table(
                ["Symbol", "Candidate Strikes", "Executed Strikes", "Direction"],
                example_rows,
            )
        )

    if trade_only_count > 0:
        reason_counts: Counter[str] = execution_alignment_summary[
            "trade_only_reason_counts"
        ]
        lines.extend(["", "### Trade-Only Reasons"])
        reason_rows = [
            [reason, str(count)] for reason, count in reason_counts.most_common()
        ]
        lines.extend(markdown_table(["Reason", "Count"], reason_rows))

    daily_presence_counts: Counter[str] = execution_alignment_summary[
        "daily_presence_counts"
    ]
    daily_match_type_counts: Counter[str] = execution_alignment_summary[
        "daily_match_type_counts"
    ]
    if daily_presence_counts:
        lines.extend(["", "### Daily Opportunities Presence"])
        daily_rows = [
            ["in_daily_file", str(int(daily_presence_counts.get("True", 0)))],
            ["not_in_daily_file", str(int(daily_presence_counts.get("False", 0)))],
            ["daily_exact_match", str(int(daily_match_type_counts.get("exact", 0)))],
            [
                "daily_shifted_match",
                str(int(daily_match_type_counts.get("shifted", 0))),
            ],
            ["daily_no_match", str(int(daily_match_type_counts.get("none", 0)))],
        ]
        lines.extend(markdown_table(["Metric", "Count"], daily_rows))

    lines.extend(["", "## Performance Segmentation"])

    dimension_titles = {
        "symbol": "By Symbol",
        "strategy_version": "By Strategy Version",
        "width": "By Width",
        "dte_band": "By DTE Band",
        "delta_band": "By Delta Band",
        "skew_bucket": "By Skew Bucket",
    }
    for dimension, title in dimension_titles.items():
        lines.extend(["", f"### {title}"])
        rows = [
            [
                str(item["group"]),
                str(item["trade_count"]),
                f"{float(item['win_rate']):.2%}",
                f"{float(item['avg_pnl']):.2f}",
                f"{float(item['median_pnl']):.2f}",
                f"{float(item['total_pnl']):.2f}",
                f"{float(item['max_drawdown_proxy']):.2f}",
            ]
            for item in segment_rows.get(dimension, [])
        ]
        lines.extend(
            markdown_table(
                [
                    "Group",
                    "Trades",
                    "Win Rate",
                    "Avg PnL",
                    "Median PnL",
                    "Total PnL",
                    "Max DD Proxy",
                ],
                rows,
            )
        )

    lines.extend(["", "## Rejection Trends (Both Logs)"])
    trend_table_rows = [
        [
            str(item["date"]),
            str(item["symbol_rejections"]),
            str(item["candidate_rejections"]),
            f"{float(item['candidate_to_symbol_ratio']):.2f}",
        ]
        for item in trend_rows
    ]
    lines.extend(
        markdown_table(
            ["Date", "Symbol Rejections", "Candidate Rejections", "Cand/Sym Ratio"],
            trend_table_rows,
        )
    )

    lines.extend(["", "### Top Rejection Reasons from Logs"])
    reason_rows = []
    for reason, count in symbol_reason_totals.most_common(10):
        reason_rows.append(["symbol_level", reason, str(count)])
    for reason, count in candidate_reason_totals.most_common(10):
        reason_rows.append(["candidate_level", reason, str(count)])
    lines.extend(markdown_table(["Source", "Reason", "Count"], reason_rows))

    lines.extend(["", "## Rejection Diagnostics Exports"])
    lines.append(
        "The following sections ingest pre-built CSV exports from "
        "rejection_diagnostics.py."
    )

    lines.extend(["", "### Detailed Reasons (from reason_summary.csv)"])
    reason_export_rows = [
        [
            str(row["source"]),
            str(row["key"]),
            str(row["count"]),
            f"{float(row['share']):.2%}",
        ]
        for row in reason_summary_rows
    ]
    lines.extend(
        markdown_table(["Source", "Reason", "Count", "Share"], reason_export_rows)
    )

    lines.extend(["", "### Executive Rollup (from bucket_summary.csv)"])
    bucket_export_rows = [
        [
            str(row["source"]),
            str(row["key"]),
            str(row["count"]),
            f"{float(row['share']):.2%}",
        ]
        for row in bucket_summary_rows
    ]
    lines.extend(
        markdown_table(["Source", "Bucket", "Count", "Share"], bucket_export_rows)
    )

    if ranking_backtest_results:
        lines.extend(["", "## Ranking Quality Backtest"])
        lines.append(
            "Comparison of realized trade outcomes across ranking score percentile buckets. "
            "Higher percentiles should show better performance if the ranking is well-calibrated."
        )
        backtest_rows = [
            [
                str(item["percentile_label"]),
                str(item["trade_count"]),
                f"{float(item['win_rate']):.2%}",
                f"{float(item['avg_pnl']):.2f}",
                f"{float(item['total_pnl']):.2f}",
            ]
            for item in ranking_backtest_results
        ]
        lines.extend(
            markdown_table(
                ["Percentile", "Count", "Win Rate", "Avg PnL", "Total PnL"],
                backtest_rows,
            )
        )

    if sensitivity_analysis_results:
        lines.extend(["", "## Sensitivity Analysis: Unlock Potential"])
        lines.append(
            "Estimated impact of loosening top rejection bottlenecks. Shows how many "
            "additional candidates could be accepted if guardrails were relaxed."
        )
        sensitivity_rows = [
            [
                str(item["scenario"]),
                str(item["unlock_count"]),
                f"{float(item['unlock_candidate_pct']):.1%}",
                str(item["target_change"]),
            ]
            for item in sensitivity_analysis_results
        ]
        lines.extend(
            markdown_table(
                ["Scenario", "Unlock Count", "% of Rejected", "Config Change"],
                sensitivity_rows,
            )
        )

    if candidate_ranking_impact_results:
        lines.extend(["", "## Candidate-Level Ranking Impact"])
        lines.append(
            "Analysis of which rejection reasons disproportionately block high-scoring candidates. "
            "High % in 'Top 25% Rejected' column indicates a critical tuning bottleneck."
        )
        impact_rows = [
            [
                str(item["rejection_reason"]),
                str(item["high_score_rejected_count"]),
                str(item["total_rejected_count"]),
                f"{float(item['high_score_pct']):.1%}",
                f"{float(item['avg_score_rejected']):.2f}",
            ]
            for item in candidate_ranking_impact_results[:15]  # Top 15 bottlenecks
        ]
        lines.extend(
            markdown_table(
                [
                    "Reason",
                    "Top 25% Rejected",
                    "Total Rejected",
                    "% of High-Score",
                    "Avg Score",
                ],
                impact_rows,
            )
        )

    lines.extend(["", "## Human Review Recommendations"])
    for index, recommendation in enumerate(recommendation_lines, start=1):
        lines.append(f"{index}. {recommendation}")

    lines.extend(["", "### Expected Impact and Confidence"])
    impact_rows = [
        [
            str(item["recommendation"]),
            str(item["expected_impact"]),
            str(item["confidence"]),
            str(item["rationale"]),
        ]
        for item in recommendation_impact_rows
    ]
    lines.extend(
        markdown_table(
            ["Recommendation", "Expected Impact", "Confidence", "Rationale"],
            impact_rows,
        )
    )

    lines.extend(
        [
            "",
            "## Artifacts",
            f"- Markdown summary: {markdown_output_path}",
            f"- Machine-readable CSV: {csv_output_path}",
        ]
    )

    return "\n".join(lines)


def build_metrics_export_rows(
    *,
    overall: MetricSummary,
    rolling_window_metrics: list[dict[str, object]],
    rolling_rejection_trends: list[dict[str, object]],
    rolling_rejection_reason_trends: list[dict[str, object]],
    ranking_backtest_results: list[dict[str, object]],
    sensitivity_analysis_results: list[dict[str, object]],
    candidate_ranking_impact_results: list[dict[str, object]],
    segment_rows: dict[str, list[dict[str, object]]],
    trend_rows: list[dict[str, object]],
    reason_summary_rows: list[dict[str, object]],
    bucket_summary_rows: list[dict[str, object]],
    recommendation_lines: list[str],
    recommendation_impact_rows: list[dict[str, str]],
    closed_records: list[dict[str, object]],
) -> list[list[str]]:
    """Build flattened report metrics for machine-readable downstream use."""
    rows: list[list[str]] = []

    overall_items = {
        "trade_count": float(overall.trade_count),
        "win_rate": overall.win_rate,
        "avg_pnl": overall.avg_pnl,
        "median_pnl": overall.median_pnl,
        "total_pnl": overall.total_pnl,
        "max_drawdown_proxy": overall.max_drawdown_proxy,
    }
    for metric_name, metric_value in overall_items.items():
        rows.append(
            [
                "performance",
                "overall",
                "all",
                metric_name,
                f"{metric_value}",
            ]
        )

    execution_alignment_summary = build_execution_alignment_summary(closed_records)
    alignment_counts: Counter[str] = execution_alignment_summary["alignment_counts"]
    direction_counts: Counter[str] = execution_alignment_summary["direction_counts"]
    rows.append(
        [
            "execution_alignment",
            "summary",
            "all",
            "exact_count",
            str(int(alignment_counts.get("exact", 0))),
        ]
    )
    rows.append(
        [
            "execution_alignment",
            "summary",
            "all",
            "shifted_count",
            str(int(alignment_counts.get("shifted", 0))),
        ]
    )
    rows.append(
        [
            "execution_alignment",
            "summary",
            "all",
            "trade_only_count",
            str(int(alignment_counts.get("trade_only", 0))),
        ]
    )
    rows.append(
        [
            "execution_alignment",
            "summary",
            "all",
            "otm_shift_count",
            str(int(direction_counts.get("otm_shift", 0))),
        ]
    )
    rows.append(
        [
            "execution_alignment",
            "summary",
            "all",
            "itm_shift_count",
            str(int(direction_counts.get("itm_shift", 0))),
        ]
    )
    rows.append(
        [
            "execution_alignment",
            "summary",
            "all",
            "avg_short_shift_abs",
            str(float(execution_alignment_summary["avg_short_shift_abs"])),
        ]
    )
    rows.append(
        [
            "execution_alignment",
            "summary",
            "all",
            "avg_long_shift_abs",
            str(float(execution_alignment_summary["avg_long_shift_abs"])),
        ]
    )

    trade_only_reason_counts: Counter[str] = execution_alignment_summary[
        "trade_only_reason_counts"
    ]
    for reason, count in trade_only_reason_counts.items():
        rows.append(
            [
                "execution_alignment",
                "trade_only_reason",
                reason,
                "count",
                str(int(count)),
            ]
        )

    daily_presence_counts: Counter[str] = execution_alignment_summary[
        "daily_presence_counts"
    ]
    daily_match_type_counts: Counter[str] = execution_alignment_summary[
        "daily_match_type_counts"
    ]
    rows.append(
        [
            "execution_alignment",
            "daily_presence",
            "all",
            "in_daily_file_count",
            str(int(daily_presence_counts.get("True", 0))),
        ]
    )
    rows.append(
        [
            "execution_alignment",
            "daily_presence",
            "all",
            "not_in_daily_file_count",
            str(int(daily_presence_counts.get("False", 0))),
        ]
    )
    for match_type in ("exact", "shifted", "none"):
        rows.append(
            [
                "execution_alignment",
                "daily_match_type",
                "all",
                f"{match_type}_count",
                str(int(daily_match_type_counts.get(match_type, 0))),
            ]
        )

    for window_metric in rolling_window_metrics:
        window_label = f"{window_metric['window_days']}d"
        for metric_name in ("trade_count", "win_rate", "avg_pnl", "total_pnl"):
            rows.append(
                [
                    "rolling_metrics",
                    "performance_window",
                    window_label,
                    metric_name,
                    str(window_metric[metric_name]),
                ]
            )

    for rolling_rejection in rolling_rejection_trends:
        window_label = f"{rolling_rejection['window_days']}d"
        rows.append(
            [
                "rolling_metrics",
                "rejection_window",
                window_label,
                "symbol_rejections",
                str(rolling_rejection["symbol_rejections"]),
            ]
        )
        rows.append(
            [
                "rolling_metrics",
                "rejection_window",
                window_label,
                "candidate_rejections",
                str(rolling_rejection["candidate_rejections"]),
            ]
        )

    for reason_trend in rolling_rejection_reason_trends:
        window_label = f"{reason_trend['window_days']}d"
        rows.append(
            [
                "rolling_metrics",
                "rejection_reason_window",
                f"{reason_trend['reason_source']}_{window_label}",
                reason_trend["reason"],
                str(reason_trend["count"]),
            ]
        )

    for backtest_result in ranking_backtest_results:
        percentile = backtest_result["percentile_label"]
        rows.append(
            [
                "ranking_backtest",
                "cohort_performance",
                percentile,
                "trade_count",
                str(backtest_result["trade_count"]),
            ]
        )
        rows.append(
            [
                "ranking_backtest",
                "cohort_performance",
                percentile,
                "win_rate",
                str(backtest_result["win_rate"]),
            ]
        )
        rows.append(
            [
                "ranking_backtest",
                "cohort_performance",
                percentile,
                "avg_pnl",
                str(backtest_result["avg_pnl"]),
            ]
        )
        rows.append(
            [
                "ranking_backtest",
                "cohort_performance",
                percentile,
                "total_pnl",
                str(backtest_result["total_pnl"]),
            ]
        )

    for sensitivity_item in sensitivity_analysis_results:
        scenario = sensitivity_item["scenario"]
        rows.append(
            [
                "sensitivity_analysis",
                "unlock_potential",
                scenario,
                "unlock_count",
                str(sensitivity_item["unlock_count"]),
            ]
        )
        rows.append(
            [
                "sensitivity_analysis",
                "unlock_potential",
                scenario,
                "unlock_pct",
                str(sensitivity_item["unlock_candidate_pct"]),
            ]
        )
        rows.append(
            [
                "sensitivity_analysis",
                "unlock_potential",
                scenario,
                "target_change",
                str(sensitivity_item["target_change"]),
            ]
        )

    for impact_result in candidate_ranking_impact_results:
        reason = impact_result["rejection_reason"]
        rows.append(
            [
                "candidate_ranking_impact",
                "bottleneck_analysis",
                reason,
                "high_score_rejected_count",
                str(impact_result["high_score_rejected_count"]),
            ]
        )
        rows.append(
            [
                "candidate_ranking_impact",
                "bottleneck_analysis",
                reason,
                "total_rejected_count",
                str(impact_result["total_rejected_count"]),
            ]
        )
        rows.append(
            [
                "candidate_ranking_impact",
                "bottleneck_analysis",
                reason,
                "high_score_pct",
                str(impact_result["high_score_pct"]),
            ]
        )
        rows.append(
            [
                "candidate_ranking_impact",
                "bottleneck_analysis",
                reason,
                "avg_score_rejected",
                str(impact_result["avg_score_rejected"]),
            ]
        )

    for dimension, items in segment_rows.items():
        for item in items:
            for metric_name in (
                "trade_count",
                "win_rate",
                "avg_pnl",
                "median_pnl",
                "total_pnl",
                "max_drawdown_proxy",
            ):
                rows.append(
                    [
                        "performance",
                        dimension,
                        str(item["group"]),
                        metric_name,
                        str(item[metric_name]),
                    ]
                )

    for trend in trend_rows:
        rows.append(
            [
                "rejections",
                "daily_trend",
                str(trend["date"]),
                "symbol_rejections",
                str(trend["symbol_rejections"]),
            ]
        )
        rows.append(
            [
                "rejections",
                "daily_trend",
                str(trend["date"]),
                "candidate_rejections",
                str(trend["candidate_rejections"]),
            ]
        )

    for row in reason_summary_rows:
        rows.append(
            [
                "rejections",
                "reason_summary",
                str(row["source"]),
                str(row["key"]),
                str(row["count"]),
            ]
        )

    for row in bucket_summary_rows:
        rows.append(
            [
                "rejections",
                "bucket_summary",
                str(row["source"]),
                str(row["key"]),
                str(row["count"]),
            ]
        )

    for index, recommendation in enumerate(recommendation_lines, start=1):
        rows.append(
            [
                "recommendations",
                "human_review",
                "all",
                f"recommendation_{index}",
                recommendation,
            ]
        )

    for index, item in enumerate(recommendation_impact_rows, start=1):
        label = f"recommendation_{index}"
        rows.append(
            [
                "recommendations",
                "impact",
                label,
                "expected_impact",
                str(item["expected_impact"]),
            ]
        )
        rows.append(
            [
                "recommendations",
                "impact",
                label,
                "confidence",
                str(item["confidence"]),
            ]
        )
        rows.append(
            [
                "recommendations",
                "impact",
                label,
                "rationale",
                str(item["rationale"]),
            ]
        )

    return rows


def parse_args() -> argparse.Namespace:
    """Parse CLI options for weekly reporting."""
    parser = argparse.ArgumentParser(
        description="Generate weekly markdown and CSV analytics reports."
    )
    parser.add_argument(
        "--analysis-dataset",
        type=Path,
        default=DEFAULT_ANALYSIS_DATASET,
        help="Path to normalized analysis dataset CSV.",
    )
    parser.add_argument(
        "--symbol-log",
        type=Path,
        default=DEFAULT_SYMBOL_LOG,
        help="Path to symbol-level rejection log CSV.",
    )
    parser.add_argument(
        "--candidate-log",
        type=Path,
        default=DEFAULT_CANDIDATE_LOG,
        help="Path to candidate-level rejection log CSV.",
    )
    parser.add_argument(
        "--reports-dir",
        type=Path,
        default=DEFAULT_REPORTS_DIR,
        help="Directory for markdown and CSV report outputs.",
    )
    parser.add_argument(
        "--start-date",
        type=str,
        default="",
        help="Inclusive start date (YYYY-MM-DD).",
    )
    parser.add_argument(
        "--end-date",
        type=str,
        default="",
        help="Inclusive end date (YYYY-MM-DD).",
    )
    parser.add_argument(
        "--dataset-date-column",
        type=str,
        default="snapshot_ts",
        help="Date column in analysis dataset for window filtering.",
    )
    parser.add_argument(
        "--symbol-date-column",
        type=str,
        default="timestamp",
        help="Date column in symbol rejection log for trend filtering.",
    )
    parser.add_argument(
        "--candidate-date-column",
        type=str,
        default="snapshot_ts",
        help="Date column in candidate rejection log for trend filtering.",
    )
    parser.add_argument(
        "--rejection-prefix",
        type=str,
        default="rejection_diagnostics",
        help="Prefix for rejection diagnostics exports in analysis/reports.",
    )
    parser.add_argument(
        "--output-prefix",
        type=str,
        default="weekly_report",
        help="Prefix for generated markdown and CSV report files.",
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=10,
        help="Maximum groups per segmentation table.",
    )
    return parser.parse_args()


def main() -> None:
    """Run weekly report generation and write markdown + CSV artifacts."""
    args = parse_args()

    required_paths = [args.analysis_dataset, args.symbol_log, args.candidate_log]
    for path in required_paths:
        if not path.exists():
            raise FileNotFoundError(f"Required input file not found: {path}")

    reason_summary_path = (
        args.reports_dir / f"{args.rejection_prefix}_reason_summary.csv"
    )
    bucket_summary_path = (
        args.reports_dir / f"{args.rejection_prefix}_bucket_summary.csv"
    )
    for path in (reason_summary_path, bucket_summary_path):
        if not path.exists():
            raise FileNotFoundError(
                "Missing rejection diagnostics export: "
                f"{path}. Run analysis/rejection_diagnostics.py first."
            )

    start_date = parse_iso_date(args.start_date)
    end_date = parse_iso_date(args.end_date)
    if args.start_date and start_date is None:
        raise ValueError("Invalid --start-date. Expected format YYYY-MM-DD.")
    if args.end_date and end_date is None:
        raise ValueError("Invalid --end-date. Expected format YYYY-MM-DD.")
    if start_date and end_date and start_date > end_date:
        raise ValueError("--start-date cannot be after --end-date.")

    dataset_header, analysis_rows_all = load_csv_rows(args.analysis_dataset)
    if not dataset_header:
        raise ValueError("Analysis dataset is empty or missing a header.")

    analysis_rows = filter_rows_by_date(
        analysis_rows_all,
        args.dataset_date_column,
        start_date,
        end_date,
    )
    closed_trade_rows = filter_rows_by_date(
        analysis_rows_all,
        "close_date",
        start_date,
        end_date,
    )
    selected_rows = [row for row in analysis_rows if as_bool(row.get("selected", ""))]

    symbol_header, symbol_rows = load_csv_rows(args.symbol_log)
    _, candidate_rows = load_csv_rows(args.candidate_log)
    symbol_rows = filter_rows_by_date(
        symbol_rows,
        args.symbol_date_column,
        start_date,
        end_date,
    )
    candidate_rows = filter_rows_by_date(
        candidate_rows,
        args.candidate_date_column,
        start_date,
        end_date,
    )

    closed_records = build_closed_trade_records(closed_trade_rows)
    overall = summarize_performance(closed_records)

    rolling_window_metrics = build_rolling_window_metrics(closed_records)
    rolling_rejection_trends = build_rolling_rejection_trends(
        symbol_rows,
        candidate_rows,
        args.symbol_date_column,
        args.candidate_date_column,
    )
    rolling_rejection_reason_trends = build_rolling_rejection_reason_trends(
        candidate_rows,
        symbol_rows,
        args.candidate_date_column,
        args.symbol_date_column,
    )

    segment_rows = {
        "symbol": build_segment_summaries(
            closed_records,
            lambda row: (row.get("symbol") or "").strip() or "(missing)",
            args.top_n,
        ),
        "strategy_version": build_segment_summaries(
            closed_records,
            lambda row: (row.get("strategy_version") or "").strip() or "(missing)",
            args.top_n,
        ),
        "width": build_segment_summaries(
            closed_records,
            lambda row: normalize_width(row.get("width", "")),
            args.top_n,
        ),
        "dte_band": build_segment_summaries(
            closed_records,
            lambda row: dte_band(row.get("dte", "")),
            args.top_n,
        ),
        "delta_band": build_segment_summaries(
            closed_records,
            lambda row: delta_band(row.get("short_delta", "")),
            args.top_n,
        ),
        "skew_bucket": build_segment_summaries(
            closed_records,
            lambda row: skew_bucket(row.get("skew_ratio", "")),
            args.top_n,
        ),
    }

    symbol_reason_totals = summarize_symbol_reasons(symbol_header, symbol_rows)
    candidate_reason_totals = summarize_candidate_reasons(candidate_rows)
    trend_rows = build_daily_rejection_trend(
        symbol_rows,
        candidate_rows,
        args.symbol_date_column,
        args.candidate_date_column,
    )

    reason_summary_rows = load_rejection_export(reason_summary_path, "reason")
    bucket_summary_rows = load_rejection_export(bucket_summary_path, "bucket")

    recommendation_lines = recommendations(overall, bucket_summary_rows, segment_rows)

    # Load ranking data and compute backtest if available
    ranking_rows = load_latest_rankings(args.reports_dir)
    ranking_backtest_results = build_ranking_quality_backtest(
        closed_trade_rows, ranking_rows
    )

    # Compute sensitivity analysis on rejection bottlenecks
    sensitivity_analysis_results = build_sensitivity_analysis(
        candidate_rows, symbol_rows
    )

    # Compute candidate-level ranking impact analysis
    candidate_ranking_impact_results = build_candidate_ranking_impact(
        candidate_rows, ranking_rows
    )
    recommendation_impact_rows = build_recommendation_impact_confidence(
        recommendation_lines,
        overall,
        sensitivity_analysis_results,
        candidate_ranking_impact_results,
    )

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    if start_date is None and end_date is None:
        window_text = "all dates"
    else:
        window_text = (
            f"{start_date.isoformat() if start_date else '-inf'} to "
            f"{end_date.isoformat() if end_date else '+inf'}"
        )

    file_suffix = (
        end_date.isoformat() if end_date else datetime.now().date().isoformat()
    )
    markdown_output_path = args.reports_dir / f"{args.output_prefix}_{file_suffix}.md"
    csv_output_path = args.reports_dir / f"{args.output_prefix}_{file_suffix}.csv"

    report_text = build_markdown_report(
        window_text=window_text,
        generated_at=now,
        total_rows=len(analysis_rows),
        selected_rows=len(selected_rows),
        closed_records=closed_records,
        overall=overall,
        rolling_window_metrics=rolling_window_metrics,
        rolling_rejection_trends=rolling_rejection_trends,
        rolling_rejection_reason_trends=rolling_rejection_reason_trends,
        ranking_backtest_results=ranking_backtest_results,
        sensitivity_analysis_results=sensitivity_analysis_results,
        candidate_ranking_impact_results=candidate_ranking_impact_results,
        segment_rows=segment_rows,
        symbol_reason_totals=symbol_reason_totals,
        candidate_reason_totals=candidate_reason_totals,
        trend_rows=trend_rows,
        reason_summary_rows=reason_summary_rows,
        bucket_summary_rows=bucket_summary_rows,
        recommendation_lines=recommendation_lines,
        recommendation_impact_rows=recommendation_impact_rows,
        markdown_output_path=markdown_output_path,
        csv_output_path=csv_output_path,
    )

    markdown_output_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_output_path.write_text(report_text, encoding="utf-8")

    metric_rows = build_metrics_export_rows(
        overall=overall,
        rolling_window_metrics=rolling_window_metrics,
        rolling_rejection_trends=rolling_rejection_trends,
        rolling_rejection_reason_trends=rolling_rejection_reason_trends,
        ranking_backtest_results=ranking_backtest_results,
        sensitivity_analysis_results=sensitivity_analysis_results,
        candidate_ranking_impact_results=candidate_ranking_impact_results,
        segment_rows=segment_rows,
        trend_rows=trend_rows,
        reason_summary_rows=reason_summary_rows,
        bucket_summary_rows=bucket_summary_rows,
        recommendation_lines=recommendation_lines,
        recommendation_impact_rows=recommendation_impact_rows,
        closed_records=closed_records,
    )
    write_csv(csv_output_path, REPORT_CSV_COLUMNS, metric_rows)

    print(f"Weekly markdown report written to: {markdown_output_path}")
    print(f"Weekly CSV artifact written to: {csv_output_path}")
    print(f"Rows in analysis dataset window: {len(analysis_rows)}")
    print(f"Closed trades analyzed: {len(closed_records)}")


if __name__ == "__main__":
    main()
